apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: resume-haus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      initContainers:
        - name: storage-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name: storage
              mountPath: /data
      containers:
      - name: app
        image: alkrauss48/resume-haus:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: storage
          mountPath: "/app/storage"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: ENVIRONMENT
          value: production
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              name: app
              key: appId
        - name: CRAFT_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: craftLicenseKey
        - name: SECURITY_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: securityKey
        - name: DB_DRIVER
          value: mysql
        - name: DB_SERVER
          value: db
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: DB_SCHEMA
          value: public
        - name: DB_TABLE_PREFIX
          valueFrom:
            secretKeyRef:
              name: app
              key: tablePrefix
        - name: CP_TRIGGER
          value: admin
        - name: PRIMARY_SITE_URL
          value: "https://resumeha.us"
        - name: GMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: app
              key: gmailUsername
        - name: GMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app
              key: gmailPassword
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: resume-haus
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 8080
