apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: resume-haus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
      containers:
      - name: db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: database
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: resume-haus
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: resume-haus
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: resume-haus
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: resume-haus
              key: rootPassword
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: resume-haus
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 3306
