apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: resume-haus
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # tls:
  #   - hosts:
  #     - resume.thecodeboss.dev
  #     secretName: ingress-tls
  rules:
    - host: foo.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app
              port:
                number: 80
