apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tcb-ingress
  namespace: labs
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - labs.thecodeboss.dev
      secretName: tcb-ingress-tls
  rules:
    - host: labs.thecodeboss.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: labs
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/permanent-redirect: https://labs.thecodeboss.dev$request_uri
spec:
  tls:
    - hosts:
      - labs.thesocietea.org
      secretName: ingress-tls
  rules:
    - host: labs.thesocietea.org
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
